openapi: 3.0.3
info:
  title: 不时不食 API
  description: 应季食谱推荐 AI Agent 后端 API
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1
    description: 开发环境

paths:
  /regions:
    get:
      summary: 获取地区列表
      description: 返回所有支持的地区选项
      operationId: getRegions
      tags:
        - 地区
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  regions:
                    type: array
                    items:
                      $ref: '#/components/schemas/Region'

  /season:
    get:
      summary: 获取当前季节
      description: 根据日期和地区计算当前季节
      operationId: getCurrentSeason
      tags:
        - 季节
      parameters:
        - name: regionId
          in: query
          required: false
          schema:
            type: string
          description: 地区 ID，不传则使用默认偏移
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Season'

  /recipes:
    get:
      summary: 获取应季菜谱推荐
      description: 根据地区、季节和用户偏好生成菜谱推荐
      operationId: getRecipes
      tags:
        - 菜谱
      parameters:
        - name: regionId
          in: query
          required: true
          schema:
            type: string
          description: 地区 ID
        - name: dietType
          in: query
          required: false
          schema:
            type: string
            enum: [all, vegetarian, vegan]
            default: all
          description: 饮食类型
        - name: spiceLevel
          in: query
          required: false
          schema:
            type: string
            enum: [none, mild, medium, hot]
            default: medium
          description: 辣度偏好
        - name: allergens
          in: query
          required: false
          schema:
            type: string
          description: 过敏食材，逗号分隔
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  season:
                    $ref: '#/components/schemas/Season'
                  recipes:
                    type: array
                    items:
                      $ref: '#/components/schemas/Recipe'
        '400':
          description: 参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: 服务器错误（AI 调用失败等）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /recipes/{recipeId}:
    get:
      summary: 获取菜谱详情
      description: 获取菜谱的完整制作步骤和食材清单
      operationId: getRecipeDetail
      tags:
        - 菜谱
      parameters:
        - name: recipeId
          in: path
          required: true
          schema:
            type: string
          description: 菜谱 ID
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipeDetail'
        '404':
          description: 菜谱不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /recipes/{recipeId}/image:
    get:
      summary: 获取菜谱图片状态
      description: 查询菜谱图片生成状态和 URL
      operationId: getRecipeImage
      tags:
        - 菜谱
      parameters:
        - name: recipeId
          in: path
          required: true
          schema:
            type: string
          description: 菜谱 ID
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [pending, ready, failed]
                  imageUrl:
                    type: string
                    nullable: true

    post:
      summary: 请求生成菜谱图片
      description: 触发 AI 生成菜品图片（异步）
      operationId: generateRecipeImage
      tags:
        - 菜谱
      parameters:
        - name: recipeId
          in: path
          required: true
          schema:
            type: string
          description: 菜谱 ID
      responses:
        '202':
          description: 已接受，后台处理中
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: pending

  /health:
    get:
      summary: 健康检查
      operationId: healthCheck
      tags:
        - 系统
      responses:
        '200':
          description: 服务正常
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok

components:
  schemas:
    Region:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          example: east
        name:
          type: string
          example: 华东地区
        seasonOffset:
          type: integer
          example: 0

    Season:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          enum: [spring, summer, autumn, winter]
        name:
          type: string
          example: 春季

    Recipe:
      type: object
      required:
        - id
        - name
        - description
        - imageStatus
        - cookingTime
        - difficulty
        - seasonalIngredients
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: 清炒时蔬
        description:
          type: string
          example: 应季蔬菜简单快炒，保留食材原味
        imageUrl:
          type: string
          nullable: true
        imageStatus:
          type: string
          enum: [pending, ready, failed]
        cookingTime:
          type: integer
          description: 分钟
          example: 15
        difficulty:
          type: string
          enum: [easy, medium, hard]
        seasonalIngredients:
          type: array
          items:
            type: string
          example: ["春笋", "荠菜", "香椿"]
        createdAt:
          type: string
          format: date-time

    RecipeDetail:
      type: object
      required:
        - recipeId
        - recipe
        - ingredients
        - steps
      properties:
        recipeId:
          type: string
        recipe:
          $ref: '#/components/schemas/Recipe'
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/Ingredient'
        steps:
          type: array
          items:
            $ref: '#/components/schemas/CookingStep'
        tips:
          type: array
          items:
            type: string

    Ingredient:
      type: object
      required:
        - name
        - amount
        - isSeasonal
      properties:
        name:
          type: string
          example: 春笋
        amount:
          type: string
          example: 200g
        isSeasonal:
          type: boolean
        allergenTags:
          type: array
          items:
            type: string

    CookingStep:
      type: object
      required:
        - order
        - instruction
      properties:
        order:
          type: integer
          minimum: 1
        instruction:
          type: string
        duration:
          type: integer
          description: 分钟
        tip:
          type: string

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          example: INVALID_REGION
        message:
          type: string
          example: 无效的地区 ID
